url: https://fafafariba.github.io
baseurl: 

# Site settings
title: See Fariba Code.
email: fariba.massah@protonmail.com
description: "Fariba Massah, Software Engineer. See her code."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/fmassah/?utm_source=portfolio&utm_medium=seefaribacode
  - title: github
    url: https://github.com/fafafariba?utm_source=portfolio&utm_medium=seefaribacode

# Build settings
markdown: kramdown
permalink: pretty
